adopcionperros/urls.py
from django.urls import path
from . import views
# importamos settings y static para las imagenes de los perritos
from django.conf import settings
from django.conf.urls.static import static
# importamos vistas predeterminadas en django
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

# REEMPLAZE post_list por index ... !!!
urlpatterns = [
    path('', views.index, name='index'),
    path('registro/', views.register_view, name='vista_registro'),
    path('login/', views.login_view, name='vista_login'),
    path('logout/', views.logout_view, name='vista_logout'),
    path('mascotas/', views.mascotas_view, name='vista_mascotas'),
    path('perrito/<int:pk>/', views.perrito_detalle_view, name='vista_perrito_detalle'),
    path('accounts/login/', views.login_view, name ='vista_login'),
    path('adopcion/completado/', views.adopcion_completa_view, name='vista_adopcion_completa'),

    #Urls Recuperacion de Contraseña
    path('reset/password/', PasswordResetView.as_view(), name='reset_password'),
    path('reset/password/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/password/confirm/P<uidb64>P<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/password/complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    
    # url para las imagenes que suben de los perritos
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

misperris/urls.py
from django.urls import path, include
from django.contrib import admin
from django.urls import path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('adopcionperros.urls')),
]

adopcionperros/models.py
from django.db import models
from django import forms
from django.utils import timezone

# Clase Mascotas
class Mascotas(models.Model):

    # Inicializamos los atributos
    DISPONIBLE = 'Disponible'
    RESCATADO = 'Rescatado'
    ADOPTADO = 'Adoptado'

    # Definimos las Opciones
    STATE_CHOICES = ((DISPONIBLE, 'Disponible'),(RESCATADO, 'Rescatado'),(ADOPTADO, 'Adoptado'))

    Imagen = models.ImageField(upload_to='upload')
    NombreMascota = models.CharField(max_length=20)
    RazaPredominante = models.CharField(max_length=15)
    Descripcion = models.TextField()
    Estado = models.CharField(max_length=10, choices=STATE_CHOICES, default=DISPONIBLE)
    FechaPublicado = models.DateTimeField(blank=True, null=True)
    
    # Comprobamos que la fecha de publicado sea la actual
    def mascota_publicada(self):
        self.FechaPublicado = timezone.now()
        self.save()

    def update(self):
        self.Estado = "Adoptado"
        self.save()     
        
    # Retornamos el nombre de la mascota
    def __str__(self):
        return self.NombreMascota       

# Clase AdoptarMascota

class AdoptarMascota(models.Model):

    Adoptador = models.CharField(max_length=45)
    MascotaAdoptada = models.CharField(max_length=20)

    # Guardamos la Adopcion
    def mascota_adoptada(self):
        self.save()

    # Enlazamos el Nombre del adoptador con el nombre de la mascota para darle un buen toque

    def __str__(self):
        cadena = "El Usuario {0} ha adopta a la Mascota {1}"
        return cadena.format(self.Adoptador, self.MascotaAdoptada)    
 

        

        

adopcionperros/forms.py
from django import forms
from django.contrib.auth.models import User

class ContactForm(forms.Form):
    Email = forms.EmailField(widget=forms.TextInput())
    Titulo = forms.CharField(widget=forms.TextInput())
    Texto = forms.CharField(widget=forms.Textarea())

class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput(render_value=False))

class RegisterForm(forms.Form):
    username = forms.CharField(label="Nombre de Usuario",widget=forms.TextInput())
    lastname = forms.CharField(label="Apellido Paterno",widget=forms.TextInput())
    firstname = forms.CharField(label="Nombre",widget=forms.TextInput())
    email = forms.EmailField(label="Correo Electronico",widget=forms.TextInput())
    password_one = forms.CharField(label="Contraseña",widget=forms.PasswordInput(render_value=False))
    password_two = forms.CharField(label="Confirmar Contraseña",widget=forms.PasswordInput(render_value=False))

    # Validamos que el Nombre de Usuario sea Unico e Irrepetible
    def clean_username(self):
        username = self.cleaned_data['username']
        try:
            u = User.objects.get(username=username)
        except User.DoesNotExist:
            return username        
        raise forms.ValidationError('ERROR: Este nombre de usuario ya existe!')

    # Validamos que el Correo sea Unico e Irrepetible
    def clean_email(self):
        email = self.cleaned_data['email']
        try:
            u = User.objects.get(email=email)
        except User.DoesNotExist:
            return email
        raise forms.ValidationError('ERROR: Este Email ya esta Registrado!')

    # Validamos la contraseña 2
    def clean_password_two(self):
        password_one = self.cleaned_data['password_one']
        password_two = self.cleaned_data['password_two']
        if password_one == password_two:
            pass
        else:
            raise forms.ValidationError('ERROR: Las Contraseñas no coinciden!')

adopcionperros/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from .models import Mascotas, AdoptarMascota
from .forms import ContactForm, LoginForm, RegisterForm
from django.contrib.auth.models import User

from django.contrib.auth import login,logout,authenticate # Importamos funciones de login logout y authenticate
from django.http import HttpResponseRedirect 

# Crea tus vistas aqui.

# Vista Principal Index.html

def index(request):
    mascotapublicada = Mascotas.objects.filter(FechaPublicado__lte=timezone.now()).order_by('FechaPublicado')
    return render(request, 'adopcionperros/index.html', {'mascotapublicada': mascotapublicada})    

# Vista de registro /registro/ donde va el formulario de registro de usuario

def register_view(request):
    form = RegisterForm()
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            usuario = form.cleaned_data['username']
            lastname = form.cleaned_data['lastname']
            firstname = form.cleaned_data['firstname']
            email = form.cleaned_data['email']
            password_one = form.cleaned_data['password_one']
            password_two = form.cleaned_data['password_two']
            u = User.objects.create_user(username=usuario,last_name=lastname,first_name=firstname,email=email,password=password_one)
            # Registramos el Usuario
            u.save()
            # Redireccionamos a la pagina de confirmacion de registro exitoso
            return render(request,'adopcionperros/registro_exitoso.html')
        else:
            ctx = {'form':form}
            return render(request,'adopcionperros/registro.html',ctx)
    ctx = {'form':form}
    return render(request,'adopcionperros/registro.html',ctx)

# Vista de log in /login/ donde va el formulario de log in de usuario

def login_view(request):
    mensaje =""
    if request.user.is_authenticated:
            return HttpResponseRedirect('/')
    else:
            if request.method == "POST":
                    form = LoginForm(request.POST)
                    if form.is_valid():
                            username = form.cleaned_data['username']
                            password = form.cleaned_data['password']
                            usuario = authenticate(username=username,password=password)
                            if usuario is not None and usuario.is_active:
                                    login(request,usuario)
                                    return HttpResponseRedirect('/')
                            else:
                                    mensaje = "Usuario y/o Password Incorrecto"
            form = LoginForm()
            ctx = {'form':form,'mensaje':mensaje}
            return render(request,'adopcionperros/login.html',ctx)

# Vista de logout /logout/ donde va el formulario de logout de usuario

def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/')

def adopcion_completa_view(request):
    return render(request, 'adopcionperros/adopcion_completa.html')

# Vista de la lista de mascotas /mascotas/ donde estan todas las mascotas de la pagina

def mascotas_view(request):
    masco = Mascotas.objects.filter(Estado="Disponible")
    ctx = {'mascota': masco}
    return render(request,'adopcionperros/mascotas.html',ctx)

# Vista en detalle de mascotas /perrito/ 
   
def perrito_detalle_view(request, pk):
    perris = get_object_or_404(Mascotas, pk=pk) 

    if (request.method == "POST"):
        Adoptador = request.user
        AdoptarMascota.objects.create(Adoptador=Adoptador, MascotaAdoptada=perris.NombreMascota)
        perris.update()

        return render(request, 'adopcionperros/adopcion_completa.html')

    else:
        ctx = {'mascotas':perris}
        return render(request,'adopcionperros/perrito_detalle.html',ctx)

adopcionperros/templates/adopcionperros/adopcion_completa.html
{% extends 'adopcionperros/base_formulario.html' %}
{% block title %} Adopcion Mascota {% endblock %}
{% block content %}

<div class="contenedor">
    <div class="exitoso">
            <h2>Estamos muy contentos ya que acabas de Adoptar a un perrito de MisPerris</h2>
    </div>
</div>
{% endblock %}

adopcionperros/templates/adopcionperros/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
    
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1, maximum-scale=1,minimum=scale=1">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="description" content="MisPerris Pagina Oficial de Adopcion de Perritos">
    <title>Inicio | MisPerris</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/fontello.css' %}">
    <link rel="shortcut icon" href="{% static 'images/favicon.png' %}">
    
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
</head>
<body>

    <header>
        <div class="contenedor">
            <h1>MisPerris</h1>
            <input type="checkbox" id="menu-bar">
            <label class="icon-menu" for="menu-bar"></label>

            <nav class="menu">
                <a href="{% url 'index' %}">Inicio</a>
                <a href="/mascotas/">Mascotas</a>
                <a href="/registro/">Registro</a>
                {% if user.is_authenticated %}
                <a href="/logout/">Log Out</a>
                {% else %}
                <a href="/login/">Log In</a>
                {% endif %}
                {% if user.is_authenticated %}
                <a href="#"> Usuario: {{ user.username }} </a>
                {% endif %}
                {% if user.is_authenticated and user.is_staff %}
                <a href="/admin/"> Administracion </a>
                {% endif %}
            </nav>
        </div>
    </header>

    <main>
        
        <div id="contenedor-slider">
            
            <div id="slider">
                    
                <section>    
                    
                    <img src="{% static 'images/carru1.png' %}" alt="Carrusel 1">
                        
                </section>
                
                <section>                
                    
                    <img src="{% static 'images/carru2.png' %}" alt="Carrusel 2">
                    
                </section>
                
                <section>
                       
                    <img src="{% static 'images/carru3.png' %}" alt="Carrusel 3">
    
                </section>

                <section>
                    
                    <img src="{% static 'images/carru4.png' %}" alt="Carrusel 4">
                    
                </section>
                
            </div>
                <div id="boton-anterior">&#60;</div>
                <div id="boton-siguiente">&#62;</div>
        </div>
        
        <section id="Introduccion">
            <h2>CONOCENOS!</h2>
            <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc mollis odio at nunc consequat feugiat. Phasellus bibendum ligula quis enim elementum, nec tincidunt ex bibendum. Praesent a rhoncus nisl, nec porttitor libero. Aliquam eleifend at libero sit amet ultricies. Quisque odio nisi, aliquam vel aliquam non, fermentum vitae mi. Aenean interdum augue ac consequat vestibulum. Morbi in aliquet nulla, in finibus nisi. Proin faucibus sollicitudin ante, dictum lobortis leo. Maecenas elementum diam a sem venenatis, nec mattis dolor luctus.
            </p>
            
            <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc mollis odio at nunc consequat feugiat. Phasellus bibendum ligula quis enim elementum, nec tincidunt ex bibendum. Praesent a rhoncus nisl, nec porttitor libero. Aliquam eleifend at libero sit amet ultricies. Quisque odio nisi, aliquam vel aliquam non, fermentum vitae mi. Aenean interdum augue ac consequat vestibulum. Morbi in aliquet nulla, in finibus nisi. Proin faucibus sollicitudin ante, dictum lobortis leo. Maecenas elementum diam a sem venenatis, nec mattis dolor luctus.
            </p>
        </section>
        
        <section id="perritos">
            <div class="contenedor">
                {% block content %}
                {% endblock %}
            </div>
        </section>
    </main>

    <footer>
        <div class="contenedor">
            <p class="copyright">MisPerris &copy; 2018</p>
            <div class="redesociales">
                <a class="icon-facebook" href="#"></a>
                <a class="icon-twitter" href="#"></a>
                <a class="icon-instagram" href="#"></a>
            </div>
        </div>
    </footer>
    
    <script src="{% static 'js/slider.js' %}"></script>
</body>    
</html>

adopcionperros/templates/adopcionperros/base_formulario.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1, maximum-scale=1,minimum=scale=1">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="description" content="MisPerris Pagina Oficial de Adopcion de Perritos">
    <title>MisPerris</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/fontello.css' %}">
    <link rel="shortcut icon" href="{% static 'images/favicon.png' %}">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

</head>
<body>
    <header>
        <div class="contenedor">
            <h1>MisPerris</h1>
            <input type="checkbox" id="menu-bar">
            <label class="icon-menu" for="menu-bar"></label>
            <nav class="menu">
                <a href="{% url 'index' %}">Inicio</a>
                <a href="/mascotas/">Mascotas</a>
                <a href="/registro/">Registro</a>
                {% if user.is_authenticated %}
                <a href="/logout/">Log Out</a>
                {% else %}
                <a href="/login/">Log In</a>
                {% endif %}
                {% if user.is_authenticated %}
                <a href="#"> Usuario: {{ user.username }} </a>
                {% endif %}
                {% if user.is_authenticated and user.is_staff %}
                <a href="/admin/"> Administracion </a>
                {% endif %}
            </nav>
        </div>
    </header>

    <main>
       
        <div id="contenedor-slider">
           
            <div id="slider">
                    
                <section>    
                    
                    <img src="{% static 'images/carru1.png' %}" alt="Carrusel 1">
                        
                </section>
                
                <section>                
                    
                    <img src="{% static 'images/carru2.png' %}" alt="Carrusel 2">
                    
                </section>
                
                <section>
                       
                    <img src="{% static 'images/carru3.png' %}" alt="Carrusel 3">
    
                </section>

                </section>
                    
                    <img src="{% static 'images/carru4.png' %}" alt="Carrusel 4">
                    
                </section>
                
            </div>
                <div id="boton-anterior">&#60;</div>
                <div id="boton-siguiente">&#62;</div>
        </div>
       
            <section id="RegistroFormulario">
                {% block content %}
                {% endblock %}
            </section>
       
    </main>

    <footer>
        <div class="contenedor">
            <p class="copyright">MisPerris &copy; 2018</p>
            <div class="redesociales">
                <a class="icon-facebook" href="#"></a>
                <a class="icon-twitter" href="#"></a>
                <a class="icon-instagram" href="#"></a>
            </div>
        </div>
    </footer>
    
    <script src="{% static 'js/slider.js' %}"></script>
    
</body>    
</html>

adopcionperros/templates/adopcionperros/index.html
{% extends 'adopcionperros/base.html' %}
{% block content %}
{% endblock %}           

adopcionperros/templates/adopcionperros/login.html
{% extends 'adopcionperros/base_formulario.html' %}
{% block title %} Login {% endblock %}
{% block content %}
<h2>INGRESA CON TU CUENTA</h2>
<div class="login">
    <form action="." method="POST">
        {% csrf_token %}
        {{ mensaje }}
        <p><label for="id_username">Username:</label> 
            <input type="text" name="username" required="" id="id_username">
        </p>
    
        <p><label for="id_password">Password:</label> 
            <input type="password" name="password" required="" id="id_password">
        </p>

        <h4>¿Quieres Recuperar tu Contraseña? Click <a href='/reset/password/'>Aqui</a></h4>

        <button class="btnlogin" type="submit" value="Login">Login</button>
        
    </form>
</div>
{% endblock %}

adopcionperros/templates/adopcionperros/mascotas.html
{% extends 'adopcionperros/base.html' %}
{% block content %}
    {% for mascotas in mascota %}
        <article>
            <h2><a href="/perrito/{{ mascotas.pk }}/" style="text-decoration: none;">{{ mascotas.NombreMascota }}</a></h2><br>
                <img src="{{ mascotas.Imagen.url }}"><br>
                <h2>Estado:</h2><h4>{{ mascotas.Estado }}</h4><br>
        </article>
    {% endfor %}
{% endblock %}

adopcionperros/templates/adopcionperros/perrito_detalle.html
{% extends 'adopcionperros/base_formulario.html' %}
{% block content %}
        <article>
            <form id="adoptarperris" method="POST">
            {% csrf_token %}
            <h2><a href="" style="text-decoration: none;">{{ mascotas }}</a></h2><br>
                <img src="{{ mascotas.Imagen.url }}"><br>
                <h2>Estado:</h2><br><h4>{{ mascotas.Estado }}</h4><br>
                <h2>Descripción:</h2><br><p>{{ mascotas.Descripcion|linebreaksbr }}</p><br>
            <h2>Raza:</h2><br><h4>{{ mascotas.RazaPredominante }}</h4><br>
            <h2>Fecha Publicado:</h2><br><h4>{{ mascotas.FechaPublicado }}</h4><br>
            {% if user.is_authenticated %}
            <button class="adoptar" type="submit">ADOPTAME</button>
            {% endif %}
            </form>
        </article>
{% endblock %}

adopcionperros/templates/adopcionperros/registro.html
{% extends 'adopcionperros/base_formulario.html' %}
{% block title %} Registro {% endblock %}
    {% block content %}
    <h2>REGISTRATE</h2>
        <div class="formulario">
            <form action="." method="POST">
                    {% csrf_token %}
                    <p><label for="id_username">Nombre de Usuario:</label> 
                    <input type="text" name="username" required="" id="id_username"></p>
        
                    <p><label for="id_lastname">Apellido Paterno:</label> 
                    <input type="text" name="lastname" required="" id="id_lastname"></p>
        
                    <p><label for="id_firstname">Nombre:</label>
                    <input type="text" name="firstname" required="" id="id_firstname"></p>
        
                    <p><label for="id_email">Correo Electronico:</label>
                    <input type="text" name="email" required="" id="id_email"></p>
        
                    <p><label for="id_password_one">Contraseña:</label>
                    <input type="password" name="password_one" required="" id="id_password_one"></p>
        
                    <p><label for="id_password_two">Confirmar Contraseña:</label>
                    <input type="password" name="password_two" required="" id="id_password_two"></p>
                    
                    <button class="btn btn-primary" type="submit">Registrarse</button>
            </form>
        </div>
{% endblock %}   

adopcionperros/templates/adopcionperros/registro_exitoso.html
{% extends 'adopcionperros/base_formulario.html' %}
{% block title %} Registro {% endblock %}
    {% block content %}
        <div class="contenedor">
            <div class="regis">
                <h2>REGISTRO EXITOSO!</h2>
                <h4>Gracias por registrarse</h4>
            </div>
            <a href="/login/" class="btn btn-primary">Iniciar Sesion</a>
        </div>
{% endblock %}   